WebDev/JEE/JSTL/src/demo/TestBean.java
package demo;

public class TestBean {
	public String getHello(){
		return "Hello motherfucker!";
	}
}

WebDev/JEE/JSTL/src/demo/UserBean.java
package demo;

public class UserBean {
	private String name;
	private String password;
	
	public UserBean(){}
	public UserBean(String name, String password){
		this.name = name;
		this.password = password;
	}
	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
}

WebDev/JEE/JSTL/WebContent/choose.when_for.each.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
	<%-- odpowiednik if-else --%>
	<c:choose>
		<c:when test='${ param.id == 1 }'>
			<b>Id równa się 1</b>
		</c:when>
		<c:when test='${ param.id == 2 }'>
			<b>Id równa się 2</b>
		</c:when>
		<c:otherwise>
			Id nie jest równe ani 1 ani 2
		</c:otherwise>
	</c:choose>
	
	<p></p>
	
	<%-- pętle --%>
	<c:forEach var="i" begin="0" end="10" step="2">
		i = <c:out value='${ i }'/> <br/>
	</c:forEach>
	
	<%-- pętla z varStatus --%>
	<c:forEach var="i" begin="0" end="5" varStatus="status">
		<c:if test='${status.first}'>
			Starting the loop(<c:out value='i = ${i}'/>)
			<br/>
		</c:if>

		<c:if test='${status.last}'>
			Finishing the loop(<c:out value='i = ${i}'/>)
		</c:if>
	</c:forEach>
</body>
</html>

WebDev/JEE/JSTL/WebContent/maps.lists.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>  

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
	<c:out value='Mapa: ${map["owoc"]}'></c:out> <br/>
	Outputing directly without 'c:out':  ${map["owoc"]}
	
	<br/>
	
	<c:forEach var='user' items='${mylist}'>
		${user.name} : ${user.password} <br/>
	</c:forEach>
	
	<!-- trochę stylowania HTML do tej samej pętli co wyżej... -->
	<br/>
	<table style="border: 2px solid gray;">
		<c:forEach var="element" items='${mylist}'>
			<tr> <td>${element.name}</td> <td>${element.password}</td> </tr>
		</c:forEach>
	</table>
</body>
</html>

WebDev/JEE/JSTL/WebContent/naglowek_parametry_if_bean.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>

<!-- O ile nie jest to konieczne nie powinno używać się w plikach jsp skrypletów javy - <%%> itp. 
	 Jest to przestarzała nie efektywna technologia, zamiast tego używa się JSTL(Java Standard Tag Library),
	 oraz EL(Expression Language). Znaczniki JSTL dzielą się na:
	 - core tags 
	 - formating tags
	 - xml tags
	 - sql tags
	 - functions tags
-->

<%-- komentarzy tworzonych za pomocą skrypletu nie widać w wyjściowym pliku html --%>


<%-- do JSTL potrzebujemy takiego nagłówka. Nie ma znaczenia czy adres uri faktycznie istnieje. --%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>


<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Tytuł</title>
</head>
<body>

	<jsp:useBean id="bean1" class="demo.TestBean" scope="page"></jsp:useBean>

	<%-- uruchamiamy accessor, bez podawania przedrostka "get" i od małej litery --%>
	<c:out value="${ bean1.hello}">
	</c:out>

	<br />

	<%-- tak pobieramy parametry za pomocą JSTL i EL --%>
	Wartość parametru 'msg':
	<c:out value="${ param.msg }"></c:out>

	<%-- instrukcje warunkowe (http://localhost:8080/JSTL/jstl.jsp?msg=hej%20tam&name=Tomek) --%>
	<p>
		<c:if test='${ param.name == "Tomek" }'>
			Cześć Tomek!
		</c:if>

		<c:if test='${ param.name != "Tomek" }'>
			Cześć nieznajomy!
		</c:if>
	</p>
</body>
</html>

WebDev/JEE/JSTL/WebContent/request.session.context_attributes.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>    
    
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
	
	<%-- inaczej niż w przypadku skrypletów, nie trzeba się odwoływać do obiektów session, context czy request by "wyciągnąć"
		 z nich atrybuty. Język EL wyszykuje te atrybuty automatycznie --%>
	<c:out value="${user1.name}"/><br/> <!-- request -->
	<c:out value="${user2.name}"/><br/> <!-- session -->
	<c:out value="${user3.name}"/><br/> <!-- context -->
	<br/>
	<%-- jednak można też być precyzyjnym za pomocą "implicit objects" --%>
	<c:out value="${requestScope.user1.name}"/><br/> <!-- request -->
	<c:out value="${sessionScope.user2.name}"/><br/> <!-- session -->
	<c:out value="${applicationScope.user3.name}"/><br/> <!-- context -->
	<br/>
	

</body>
</html>